// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonthlyScheduler.Data;

#nullable disable

namespace MonthlyScheduler.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20251104050614_AddCategoryFooterText")]
    partial class AddCategoryFooterText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MonthlyScheduler.Models.CategoryFooterText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FooterText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("CategoryFooterTexts");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DailySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneratedScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedScheduleId");

                    b.ToTable("DailySchedules");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DutyTypeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceScheduleId");

                    b.ToTable("DutyAssignments");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExemptFromServiceMax")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEveningDuty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMonthlyDuty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMorningDuty")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWednesdayDuty")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManualAssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManuallyScheduled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonthlyDutyFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndexAM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndexPM")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndexWednesday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SkipLastSundayEvening")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DutyTypes");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.GeneratedSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month");

                    b.ToTable("GeneratedSchedules");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeFromScheduling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSubmittedForm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.MemberDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DutyTypeId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ScheduleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyScheduleId");

                    b.HasIndex("DutyTypeId");

                    b.HasIndex("MemberId");

                    b.ToTable("ScheduleAssignments");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ServiceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchedules");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DailySchedule", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.GeneratedSchedule", "Schedule")
                        .WithMany("DailySchedules")
                        .HasForeignKey("GeneratedScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyAssignment", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.DutyType", "DutyType")
                        .WithMany("DutyAssignments")
                        .HasForeignKey("DutyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.Member", "Member")
                        .WithMany("Assignments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.ServiceSchedule", "ServiceSchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("ServiceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyType");

                    b.Navigation("Member");

                    b.Navigation("ServiceSchedule");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.MemberDuty", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.DutyType", "DutyType")
                        .WithMany("MemberDuties")
                        .HasForeignKey("DutyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.Member", "Member")
                        .WithMany("AvailableDuties")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ScheduleAssignment", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.DailySchedule", "DailySchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("DailyScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.DutyType", "DutyType")
                        .WithMany()
                        .HasForeignKey("DutyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailySchedule");

                    b.Navigation("DutyType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DailySchedule", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyType", b =>
                {
                    b.Navigation("DutyAssignments");

                    b.Navigation("MemberDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.GeneratedSchedule", b =>
                {
                    b.Navigation("DailySchedules");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.Member", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AvailableDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ServiceSchedule", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
