// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonthlyScheduler.Data;

#nullable disable

namespace MonthlyScheduler.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    [Migration("20251020030127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("MonthlyScheduler.Models.DutyAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServiceScheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DutyTypeId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ServiceScheduleId");

                    b.ToTable("DutyAssignments");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefaultEvening")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefaultMorning")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefaultWednesday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DutyTypes");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeFromScheduling")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasSubmittedForm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.MemberDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DutyTypeId");

                    b.HasIndex("MemberId");

                    b.ToTable("MemberDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ServiceSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ServiceSchedules");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyAssignment", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.DutyType", "DutyType")
                        .WithMany("DutyAssignments")
                        .HasForeignKey("DutyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.Member", "Member")
                        .WithMany("Assignments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.ServiceSchedule", "ServiceSchedule")
                        .WithMany("Assignments")
                        .HasForeignKey("ServiceScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyType");

                    b.Navigation("Member");

                    b.Navigation("ServiceSchedule");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.MemberDuty", b =>
                {
                    b.HasOne("MonthlyScheduler.Models.DutyType", "DutyType")
                        .WithMany("MemberDuties")
                        .HasForeignKey("DutyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonthlyScheduler.Models.Member", "Member")
                        .WithMany("AvailableDuties")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyType");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.DutyType", b =>
                {
                    b.Navigation("DutyAssignments");

                    b.Navigation("MemberDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.Member", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AvailableDuties");
                });

            modelBuilder.Entity("MonthlyScheduler.Models.ServiceSchedule", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
